### ISSUE TITLE
Unable to connect to pool "test"

### ISSUE THREAD

**Issue by covepark** [hyperledger/indy-cli-rs#10]
I configured local indy network on AWS(not using docker) following the latest guide in indy-node.

I successfully cloned and built indy-cli-rs.
>>git clone https://github.com/hyperledger/indy-cli-rs
>>sudo apt-get install -y cmake cargo
>>cargo build (in indy-cli-rs directory)
>>cargo run (in indy-cli-rs directory)

I created "test" pool on my local network then
>>indy-cli-rs> pool create test gen_txn_file=/var/lib/indy/sandbox/pool_transactions_genesis)

Then I tried to connect pool, "Unable to connect pool test" error occurs.
>>indy-cli-rs> pool connect test

I couldn't find any error log or message except for "Unable to connect pool test"

How can I resolve it? Are there any references or error messages that I am able to find out?

Here's my pool_transactions_genesis file

{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"15.165.101.195","client_port":9702,"node_ip":"43.203.35.120","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node2","blskey":"37rAPpXVoxzKhz7d9gkUe52XuXryuLXoM6P6LbWDB7LSbG62Lsb33sfG7zqS8TK1MXwuCHj1FKNzVpsnafmqLG1vXN88rt38mNFs9TENzm4QHdBzsvCuoBnPH7rpYYDo9DZNJePaDvRvqJKByCabubJz3XXKbEeshzpz4Ma5QYpJqjk","blskey_pop":"Qr658mWZ2YC8JXGXwMDQTzuZCWF7NK9EwxphGmcBvCh6ybUuLxbG65nsX4JvD4SPNtkJ2w9ug1yLTj6fgmuDg41TgECXjLCij3RMsV8CwewBVgVN67wsA45DFWvqvLtu4rjNnE9JbdFTc1Z4WCPA3Xan44K1HoHAq9EVeaRYs8zoF5","client_ip":"15.164.141.55","client_port":9704,"node_ip":"15.164.158.139","node_port":9703,"services":["VALIDATOR"]},"dest":"8ECVSk179mjsjKRLWiQtssMLgp6EPhWXtaYyStWPSGAb"},"metadata":{"from":"EbP4aYNeTHL6q385GuVpRV"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"1ac8aece2a18ced660fef8694b61aac3af08ba875ce3026a160acbc3a3af35fc"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node3","blskey":"3WFpdbg7C5cnLYZwFZevJqhubkFALBfCBBok15GdrKMUhUjGsk3jV6QKj6MZgEubF7oqCafxNdkm7eswgA4sdKTRc82tLGzZBd6vNqU8dupzup6uYUf32KTHTPQbuUM8Yk4QFXjEf2Usu2TJcNkdgpyeUSX42u5LqdDDpNSWUK5deC5","blskey_pop":"QwDeb2CkNSx6r8QC8vGQK3GRv7Yndn84TGNijX8YXHPiagXajyfTjoR87rXUu4G4QLk2cF8NNyqWiYMus1623dELWwx57rLCFqGh7N4ZRbGDRP4fnVcaKg1BcUxQ866Ven4gw8y4N56S5HzxXNBZtLYmhGHvDtk6PFkFwCvxYrNYjh","client_ip":"52.79.57.108","client_port":9706,"node_ip":"3.37.2.242","node_port":9705,"services":["VALIDATOR"]},"dest":"DKVxG2fXXTU8yT5N7hGEbXB3dfdAnYv1JczDUHpmDxya"},"metadata":{"from":"4cU41vWW82ArfxJxHkzXPG"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"7e9f355dffa78ed24668f0e0e369fd8c224076571c51e2ea8be5f26479edebe4"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node4","blskey":"2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw","blskey_pop":"RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP","client_ip":"15.164.80.147","client_port":9708,"node_ip":"3.36.37.73","node_port":9707,"services":["VALIDATOR"]},"dest":"4PS3EDQ3dW1tci1Bp6543CfuuebjFrg36kLAUcskGfaA"},"metadata":{"from":"TWwCRQRZ2ZHMJFn9TzLp7W"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"aa5e817d7cc626170eca175822029339a444eb0ee8f0bd20d3b0b76e566fb008"},"ver":"1"}
~

Version
Ubuntu = 20.04
Indy-node = 1.13.2
Indy-plenum = 1.131
Indy-cli-rs = 0.1.0

**Comment by WadeBarnes** [comment]
Where in relation to the nodes is the indy-cli instance?
Are you able to use `nc` from that location to ensure the node's client ports are open?
Are you able to connect to an existing network, Sovrin, BCovrin, or Indicio, using the indy-cli?
What is the state of the nodes/network?
  - `sudo validator-info`
  - `sudo validator-info -v` for more details
What steps/instructions did you follow for the installation and setup?

Things to verify:
```
cat /etc/indy/indy_config.py
- Ensure network configuration is correct.
cat /etc/indy/indy.env
- Verify node alias and IPs
cat /var/lib/indy/net3/domain_transactions_genesis
- Verify the correct content.
cat /var/lib/indy/net3/pool_transactions_genesis
- Verify the correct content.
```

Logs:
```
sudo systemctl status indy-node
sudo journalctl -u indy-node 
sudo journalctl -u indy-node-control
/var/log/indy/<networkname>/<validator_alias>.log
/var/log/indy/node_control.log
```

**Comment by WadeBarnes** [comment]
If you determine you can connect to an existing network using the indy-cli, then this is not an indy-cli issue and I can transfer the issue to `hyperledger/indy-node`.  So, please start there.

**Comment by covepark** [comment]
Thank you for letting me know the exact point I have to check.
I check it out all of your suggestions.
It's the matter of IP setting.
Appreciate it.

**Comment by WadeBarnes** [comment]
To confirm.  The issue was with your indy-node configuration.  Correct?

**Comment by WadeBarnes** [comment]
Closing this as resolved.  Please reopen if this is not the case.
